<#
.SYNOPSIS
  Populate the VA IaT Location Reference Catalog locally and open a GitHub PR.

.DESCRIPTION
  - Uses VA_API_KEY from the current PowerShell environment only.
  - Does not write VA_API_KEY to disk.
  - Fetches public VA Facilities API data using existing Python scripts.
  - Normalizes, validates, builds release candidate artifacts, commits generated data/evidence, and opens a PR.

.REQUIREMENTS
  - git
  - gh
  - python
  - authenticated gh session with repo and workflow scope

.SAFETY
  Public-source-only. No internal VA exports. No PII/PHI. No ServiceNow/CMDB exports.
#>

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3.0

$StartTime = Get-Date
$StepNo = 0

function Step {
    param([string]$Message)
    $script:StepNo++
    $Elapsed = [int]((Get-Date) - $script:StartTime).TotalSeconds
    Write-Host ''
    Write-Host ('===== {0:D2} :: {1} | elapsed={2}s =====' -f $script:StepNo, $Message, $Elapsed)
}

function Fail {
    param([string]$Message)
    throw $Message
}

function Require-Command {
    param([string]$Name)
    $Cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if (-not $Cmd) { Fail "Required command not found: $Name" }
    return $Cmd.Source
}

$RepoPath = Join-Path $env:USERPROFILE 'Desktop\VA-IaT-LocationCatalog-Pilot\va-location-reference-catalog'
$FullRepo = 'novakprotocol/va-location-reference-catalog'
$Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$WorkBranch = "work/populate-public-va-facilities-$Stamp"

Step 'VERIFY TOOLS AND REPO'
Require-Command git | Out-Host
Require-Command gh | Out-Host
Require-Command python | Out-Host

if (-not (Test-Path -LiteralPath $RepoPath)) {
    Fail "Repo path not found: $RepoPath"
}

Set-Location -LiteralPath $RepoPath
Write-Host "REPO_PATH=$RepoPath"
Write-Host "GITHUB_REPO=$FullRepo"

gh auth status

if (-not $env:VA_API_KEY) {
    Fail 'VA_API_KEY is not set in this PowerShell session. Set it in memory only: $env:VA_API_KEY = ''...'''
}

Step 'SYNC MAIN AND CREATE WORK BRANCH'
git checkout main
git pull --ff-only origin main
git checkout -B $WorkBranch

Step 'RUN PUBLIC SOURCE FETCH'
python scripts/fetch_va_facilities.py

Step 'NORMALIZE PUBLIC SOURCE DATA'
python scripts/normalize_va_facilities.py

Step 'VALIDATE CATALOG'
python scripts/validate_catalog.py

Step 'BUILD RELEASE CANDIDATE'
python scripts/build_release_candidate.py

Step 'REMOVE API KEY FROM PROCESS ENVIRONMENT'
Remove-Item Env:\VA_API_KEY -ErrorAction SilentlyContinue
Write-Host 'VA_API_KEY_REMOVED_FROM_ENV=PASS'

Step 'SHOW GENERATED FILES'
git status --short

Step 'COMMIT GENERATED DATA AND EVIDENCE'
git add data evidence

$HasStagedChanges = $false
git diff --cached --quiet
$HasStagedChanges = ($LASTEXITCODE -ne 0)

if (-not $HasStagedChanges) {
    Fail 'No generated data/evidence changes were staged. Nothing to PR.'
}

git commit -m 'data: add public VA facilities catalog candidate'

Step 'PUSH BRANCH'
git push -u origin $WorkBranch

Step 'OPEN PR'
$Body = @"
## Purpose

Add a generated public-source VA Facilities catalog candidate.

## Boundary

- Public source data only.
- No VA internal exports.
- No PII/PHI.
- No employee contact data.
- No tickets.
- No ServiceNow exports.
- No CMDB exports.
- No credentials or tokens.
- No production write-back.

## Validation

Generated by local script:

```text
python scripts/fetch_va_facilities.py
python scripts/normalize_va_facilities.py
python scripts/validate_catalog.py
python scripts/build_release_candidate.py
```

Owner review required before treating any output as approved.
"@

gh pr create --title 'data: add public VA facilities catalog candidate' --body $Body --base main --head $WorkBranch

Step 'DONE'
Write-Host ''
Write-Host 'RESULT=PASS'
Write-Host "GITHUB_REPO=$FullRepo"
Write-Host "BRANCH=$WorkBranch"
Write-Host "HEAD=$(git rev-parse --short HEAD)"
Write-Host "LOCAL_REPO_PATH=$RepoPath"
Write-Host ''
